Change behavior when handling an OFPBAC_BAD_OUT_PORT error message
kytos/flow_manager pull request #88
Opened 2020-09-17 17:40 UTC by gleybersonandrade

This PR changes the behavior when handling an OFPBAC_BAD_OUT_PORT error message, checking the interface config with OFPPC_NO_FWD flag.

2020-10-01 17:51 UTC, hdiogenes requested changes

2020-10-01 17:51 UTC, hdiogenes commented on main.py
> +                    iface = switch.get_interface_by_port_no(action.port)
I feel like there's something wrong going on here. `action.port` can act the same as `action.port.value`? Without diving into the details, it looks like `action.port` should have a setter (maybe defined as a Python `property`) and try to be always the same kind of object.

2020-10-01 17:51 UTC, hdiogenes commented on main.py
> +from pyof.v0x04.common.port import PortConfig as PortConfig04
To me, these imports are too specific to be here. More on that below.

2020-10-01 17:51 UTC, hdiogenes commented on main.py
> +           message.code == BadActionCode04.OFPBAC_BAD_OUT_PORT):
Try to think this way: when we implement OpenFlow 1.4 in `python-openflow`, will we have to come back here and also add support for it? Could we try to make this more "future-proof"?

2020-10-01 17:51 UTC, hdiogenes commented on main.py
> +                        iface.config = PortConfig04.OFPPC_NO_FWD
Same thing here. There should be a function somewhere that returned the right object for any `pyof` supported version.

2020-10-01 18:52 UTC, hdiogenes commented on main.py
> +                        iface.config = PortConfig04.OFPPC_NO_FWD
Something like this, just to have an idea of what I'm talking about:

```
port_config = pyof.get_port_config_for_version(connection.protocol.version)
iface.config = port_config.OFPPC_NO_FWD
```

2020-10-15 13:23 UTC, josemauro commented
The changes in this PR were moved and improved in PR #92.

2020-10-15 13:50 UTC, closed without merging